trigger:
- main

pool: 
  name: "ic-pool" 

steps:

- script: |
    echo "Region: $IC_REGION"
    echo "APIKEY: $IC_API_KEY"
    echo "Initializing Terraform..."
    terraform init
    
    echo "Applying Terraform configuration..."
    terraform apply -auto-approve
  displayName: 'Run Terraform Init and Apply'
